name: mobile_app
description: Flutter app for uploading face images to a Flask server.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ðŸ“¸ For taking photos
  image_picker: ^1.0.4

  # ðŸŒ For sending HTTP requests
  http: ^0.13.6

  multicast_dns: ^0.3.0

  # ðŸ” For detecting file types (e.g., image/jpeg)
  mime: ^1.0.4

  # ðŸ“ For handling file paths
  path: ^1.8.3

  # ðŸ“¦ For parsing HTTP headers and multipart data
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
